import React, { useMemo, useState } from 'react';
import { FlatList, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { Image } from 'expo-image';
import { MaterialIcons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useApp } from '@/contexts/AppContext';
import { BOTTOM_NAV_CONTENT_GAP, scale } from '@/constants/responsive';
import { MEALS, PDF_BOOKS, PRINT_ITEMS, PRINT_WORKSHOPS, RESTAURANTS } from '@/services/servicesHub';
import { Chips, localize, money, PURPLE, Rating, ServiceHeader } from '@/components/services/ServicePrimitives';

export default function ServiceSection() {
 const { section } = useLocalSearchParams<{section:string}>(); const router=useRouter(); const insets=useSafeAreaInsets(); const {colors,language}=useApp(); const isAr=language==='ar'; const lb=(en:string,fr:string,ar:string)=>language==='fr'?fr:isAr?ar:en;
 const [query,setQuery]=useState(''); const [tab,setTab]=useState(section==='restaurants'?'restaurants':'products'); const [chip,setChip]=useState('all');
 const bottom=insets.bottom+scale(80)+BOTTOM_NAV_CONTENT_GAP; const textAlign={textAlign:(isAr?'right':'left') as 'right'|'left'};
 const title=section==='restaurants'?lb('Restaurants','Restaurants','المطاعم'):section==='pdf_books'?lb('PDF Books','Livres PDF','كتب PDF'):lb('Print on demand','Impression à la demande','الطباعة عند الطلب');
 const placeholder=section==='restaurants'?lb('A dish or restaurant...','Un plat ou un restaurant...','طبق أو مطعم...'):section==='pdf_books'?lb('A book, author or store...','Un livre, un auteur ou une boutique...','كتاب أو مؤلف أو متجر...'):lb('An item or workshop...','Un article ou un atelier...','منتج أو ورشة...');
 const restaurantData=useMemo(()=>RESTAURANTS.filter(r=>localize(language,r.name).toLowerCase().includes(query.toLowerCase())&&(chip!=='open'||r.isOpen)),[language,query,chip]);
 const mealData=useMemo(()=>MEALS.filter(m=>localize(language,m.name).toLowerCase().includes(query.toLowerCase())),[language,query]);
 const bookData=useMemo(()=>PDF_BOOKS.filter(b=>(localize(language,b.title)+b.author+b.storeName).toLowerCase().includes(query.toLowerCase())&&(chip==='all'||chip==='language'||chip==='under'||b.category===chip)&&(chip!=='under'||b.price<2000)),[language,query,chip]);
 const printData=useMemo(()=>PRINT_ITEMS.filter(p=>localize(language,p.name).toLowerCase().includes(query.toLowerCase())&&(chip==='all'||p.category===chip)),[language,query,chip]);
 const tabs=(a:string,b:string)=> <View style={[s.tabs,isAr&&s.rtl]}>{[[section==='restaurants'?'meals':'products',a],[section==='restaurants'?'restaurants':'workshops',b]].map(([id,label])=><Pressable key={id} onPress={()=>setTab(id)} style={[s.tab,tab===id&&s.tabActive]}><Text style={[s.tabText,{color:tab===id?PURPLE:colors.textSecondary}]}>{label}</Text></Pressable>)}</View>;
 if(!['restaurants','pdf_books','print_pod'].includes(section||'')) return <SafeAreaView style={[s.safe,{backgroundColor:colors.background}]}><ServiceHeader title={lb('Not found','Introuvable','غير موجود')} isAr={isAr}/></SafeAreaView>;
 return <SafeAreaView edges={['top']} style={[s.safe,{backgroundColor:section==='pdf_books'?'#FFF':PURPLE}]}><KeyboardAvoidingView style={s.safe} behavior={Platform.OS==='ios'?'padding':'height'}><ServiceHeader title={title} search={placeholder} query={query} onQuery={setQuery} isAr={isAr} light={section==='pdf_books'}/>
  <View style={[s.body,{backgroundColor:colors.background}]}>
  {section==='restaurants'&&tabs(lb('Meals','Plats','الأطباق'),lb('Restaurants','Restaurants','المطاعم'))}{section==='print_pod'&&tabs(lb('Products','Produits','المنتجات'),lb('Workshops','Ateliers','الورش'))}
  {section==='restaurants'?<Chips values={[{id:'all',label:lb('All','Tout','الكل')},{id:'open',label:lb('Open','Ouvert','مفتوح')},{id:'fast',label:lb('Fast delivery','Livraison rapide','توصيل سريع')}]} active={chip} onChange={setChip} isAr={isAr} colors={colors}/>:section==='pdf_books'?<Chips values={[['all',lb('All','Tous','الكل')],['commerce',lb('Business','Commerce','التجارة')],['cuisine',lb('Cooking','Cuisine','الطبخ')],['etudes',lb('Studies','Études','الدراسة')],['budget',lb('Budget','Budget','الميزانية')],['language',lb('Language','Langue','اللغة')],['under',lb('Under 2,000','Sous 2 000','أقل من 2000')]].map(x=>({id:x[0],label:x[1]}))} active={chip} onChange={setChip} isAr={isAr} colors={colors}/>:<Chips values={[{id:'all',label:lb('All','Tout','الكل')},{id:'tshirts',label:'T-shirts'},{id:'mugs',label:lb('Mugs','Mugs','أكواب')},{id:'documents',label:lb('Documents','Documents','مستندات')}]} active={chip} onChange={setChip} isAr={isAr} colors={colors}/>} 
  {section==='restaurants'&&tab==='restaurants'?<FlatList data={restaurantData} keyExtractor={x=>x.id} contentContainerStyle={{padding:scale(14),paddingBottom:bottom}} renderItem={({item:r})=><Pressable onPress={()=>router.push(`/services/restaurant/${r.id}` as any)} style={[s.restaurant,{backgroundColor:colors.surface}]}><Image source={r.cover} style={s.cover}/><Image source={r.logo} style={[s.logo,{left:isAr?undefined:scale(14),right:isAr?scale(14):undefined}]}/><View style={s.restaurantInfo}><View style={[s.row,isAr&&s.rtl]}><Text style={[s.name,{color:colors.textPrimary},textAlign]}>{localize(language,r.name)}</Text>{r.verified&&<MaterialIcons name="verified" size={18} color="#2563EB"/>}</View><Rating rating={r.rating} reviews={r.reviews} color={colors.textSecondary}/><Text style={[s.meta,{color:colors.textSecondary},textAlign]}>{r.city}</Text><View style={[s.rowWrap,isAr&&s.rtl]}><Text style={[s.pill,{backgroundColor:r.isOpen?'#DCFCE7':'#FEE2E2',color:r.isOpen?'#166534':'#991B1B'}]}>{r.isOpen?lb('Open','Ouvert','مفتوح'):lb('Closed','Fermé','مغلق')}</Text><Text style={[s.meta,{color:colors.textSecondary}]}>🏍 {r.etaMin} – {r.etaMax} min</Text><Text style={[s.meta,{color:colors.textSecondary}]}>🪙 {money(r.deliveryFee)}</Text></View></View></Pressable>}/>:null}
  {section==='restaurants'&&tab==='meals'?<FlatList data={mealData} keyExtractor={x=>x.id} contentContainerStyle={{padding:scale(14),paddingBottom:bottom}} renderItem={({item:m})=>{const r=RESTAURANTS.find(x=>x.id===m.restaurantId)!;return <Pressable onPress={()=>router.push(`/services/restaurant/${r.id}` as any)} style={[s.meal,isAr&&s.rtl,{backgroundColor:colors.surface}]}><Image source={m.image} style={s.mealImage}/><View style={{flex:1}}><Text style={[s.name,{color:colors.textPrimary},textAlign]}>{localize(language,m.name)}</Text><Text style={[s.meta,{color:colors.textSecondary},textAlign]}>{localize(language,r.name)}</Text><Text style={s.price}>{money(m.price)}</Text></View></Pressable>}}/>:null}
  {section==='pdf_books'?<FlatList data={bookData} numColumns={2} keyExtractor={x=>x.id} columnWrapperStyle={s.columns} contentContainerStyle={{padding:scale(12),paddingBottom:bottom}} renderItem={({item:b})=><Pressable onPress={()=>router.push(`/services/book/${b.id}` as any)} style={[s.book,{backgroundColor:colors.surface}]}><View><Image source={b.cover} style={s.bookImage} contentFit="cover"/><Text style={s.pdf}>PDF</Text><MaterialIcons name="favorite-border" size={22} color={PURPLE} style={s.heart}/></View><Text numberOfLines={2} style={[s.name,{color:colors.textPrimary},textAlign]}>{localize(language,b.title)}</Text><Text style={s.price}>{money(b.price)}</Text><Rating rating={b.rating} reviews={b.reviews} color={colors.textSecondary}/><Text numberOfLines={1} style={[s.meta,{color:colors.textSecondary},textAlign]}>{b.storeName}</Text><View style={s.preview}><Text style={s.previewText}>{lb('Preview','Aperçu','معاينة')}</Text></View></Pressable>} ListFooterComponent={<Text style={[s.info,{color:colors.textSecondary}]}>{lb('Download after seller confirmation.','Téléchargement après confirmation du vendeur.','التنزيل بعد تأكيد البائع.')}</Text>}/>:null}
  {section==='print_pod'&&tab==='products'?<FlatList data={printData} numColumns={2} keyExtractor={x=>x.id} columnWrapperStyle={s.columns} contentContainerStyle={{padding:scale(12),paddingBottom:bottom}} renderItem={({item:p})=>{const w=PRINT_WORKSHOPS.find(x=>x.id===p.workshopId)!;return <Pressable onPress={()=>router.push(`/services/print/${p.id}` as any)} style={[s.book,{backgroundColor:colors.surface}]}><Image source={p.image} style={s.productImage}/><Text numberOfLines={2} style={[s.name,{color:colors.textPrimary},textAlign]}>{localize(language,p.name)}</Text><Text style={[s.meta,{color:colors.textSecondary},textAlign]}>{p.options.sizes?.join(' · ')||p.category}</Text><Text style={s.price}>{money(p.basePrice)}</Text><Text numberOfLines={1} style={[s.meta,{color:colors.textSecondary}]}>{localize(language,w.name)}</Text><Rating rating={w.rating} reviews={w.reviews}/><Text style={s.eta}>{lb('Production','Fabrication','التصنيع')} {p.etaHours}h</Text><View style={s.action}><Text style={s.actionText}>{lb('Customize','Personnaliser','تخصيص')}</Text></View></Pressable>}}/>:null}
  {section==='print_pod'&&tab==='workshops'?<ScrollView contentContainerStyle={{padding:scale(14),paddingBottom:bottom}}>{PRINT_WORKSHOPS.map(w=><Pressable key={w.id} onPress={()=>router.push(`/services/workshop/${w.id}` as any)} style={[s.workshop,isAr&&s.rtl,{backgroundColor:colors.surface}]}><MaterialIcons name="storefront" size={36} color={PURPLE}/><View style={{flex:1}}><Text style={[s.name,{color:colors.textPrimary},textAlign]}>{localize(language,w.name)}</Text><Text style={[s.meta,{color:colors.textSecondary},textAlign]}>{w.city} · {w.productIds.length} {lb('products','produits','منتجات')}</Text><Rating rating={w.rating} reviews={w.reviews}/></View><MaterialIcons name={isAr?'chevron-left':'chevron-right'} size={26} color={colors.textSecondary}/></Pressable>)}</ScrollView>:null}
  </View></KeyboardAvoidingView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1},body:{flex:1},rtl:{flexDirection:'row-reverse'},tabs:{height:scale(50),flexDirection:'row',paddingHorizontal:scale(14)},tab:{flex:1,alignItems:'center',justifyContent:'center',borderBottomWidth:2,borderColor:'transparent'},tabActive:{borderColor:PURPLE},tabText:{fontFamily:'Cairo-Bold',fontSize:scale(14)},restaurant:{borderRadius:16,overflow:'hidden',marginBottom:14},cover:{width:'100%',height:scale(145)},logo:{position:'absolute',top:scale(112),width:scale(66),height:scale(66),borderRadius:33,borderWidth:3,borderColor:'#FFF'},restaurantInfo:{padding:scale(14),paddingTop:scale(37),gap:4},row:{flexDirection:'row',alignItems:'center',gap:5},rowWrap:{flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:9,marginTop:5},name:{fontFamily:'Cairo-Bold',fontSize:scale(14),flexShrink:1},meta:{fontFamily:'Cairo-Regular',fontSize:scale(12)},pill:{fontFamily:'Cairo-SemiBold',fontSize:scale(11),paddingHorizontal:10,paddingVertical:4,borderRadius:12},meal:{padding:10,borderRadius:16,marginBottom:10,flexDirection:'row',gap:12},mealImage:{width:scale(94),height:scale(82),borderRadius:12},price:{fontFamily:'Cairo-Bold',fontSize:scale(14),color:PURPLE},columns:{justifyContent:'space-between',gap:10},book:{width:'48.5%',borderRadius:16,padding:9,marginBottom:12,gap:4},bookImage:{width:'100%',height:scale(190),borderRadius:10},productImage:{width:'100%',height:scale(132),borderRadius:10},pdf:{position:'absolute',top:6,left:6,backgroundColor:'#DC2626',color:'#FFF',fontFamily:'Cairo-Bold',fontSize:10,paddingHorizontal:6,paddingVertical:2,borderRadius:5},heart:{position:'absolute',right:7,top:7,backgroundColor:'#FFF',borderRadius:15,padding:4},preview:{minHeight:48,borderWidth:1,borderColor:PURPLE,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:4},previewText:{color:PURPLE,fontFamily:'Cairo-Bold',fontSize:12},info:{fontFamily:'Cairo-Regular',fontSize:12,textAlign:'center',padding:16},eta:{fontFamily:'Cairo-SemiBold',fontSize:10,color:'#166534',backgroundColor:'#DCFCE7',padding:5,borderRadius:8},action:{minHeight:48,backgroundColor:PURPLE,borderRadius:12,alignItems:'center',justifyContent:'center'},actionText:{fontFamily:'Cairo-Bold',fontSize:12,color:'#FFF'},workshop:{minHeight:92,borderRadius:16,padding:14,marginBottom:10,flexDirection:'row',alignItems:'center',gap:12}});
