import React, { useMemo, useState } from 'react';
import { FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { Image } from 'expo-image';
import { MaterialIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useApp } from '@/contexts/AppContext';
import { BOTTOM_NAV_CONTENT_GAP, scale } from '@/constants/responsive';
import { PDF_BOOKS, RESTAURANTS, SERVICE_CATEGORIES, servicesCounts } from '@/services/servicesHub';
import { localize, money, PURPLE, Rating } from '@/components/services/ServicePrimitives';

export default function ServicesTab() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { width } = useWindowDimensions();
  const { colors, language } = useApp(); const isAr = language === 'ar';
  const lb = (en: string, fr: string, ar: string) => language === 'fr' ? fr : isAr ? ar : en;
  const [query, setQuery] = useState(''); const cols = width < 720 ? 2 : 3;
  const categories = useMemo(() => SERVICE_CATEGORIES.filter(c => localize(language, c.name).toLowerCase().includes(query.toLowerCase())), [language, query]);
  const restaurant = RESTAURANTS[0]; const book = PDF_BOOKS[0];
  return <SafeAreaView edges={['top']} style={[styles.safe, { backgroundColor: PURPLE }]}>
    <KeyboardAvoidingView style={styles.safe} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>
    <View style={styles.header}><Text style={styles.headerTitle}>{lb('Services', 'Services', 'الخدمات')}</Text><View style={[styles.search, isAr && styles.rtl]}><MaterialIcons name="search" size={21} color="#64748B" /><TextInput value={query} onChangeText={setQuery} returnKeyType="search" placeholder={lb('Search a service...', 'Rechercher un service…', 'ابحث عن خدمة…')} placeholderTextColor="#64748B" style={[styles.input, { textAlign: isAr ? 'right' : 'left' }]} /></View></View>
    <FlatList key={cols} data={categories} numColumns={cols} keyExtractor={x => x.id} columnWrapperStyle={[styles.gridRow, isAr && styles.rtl]} contentContainerStyle={{ padding: scale(14), paddingBottom: insets.bottom + scale(80) + BOTTOM_NAV_CONTENT_GAP }} style={{ backgroundColor: colors.background }} renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={localize(language, item.name)} onPress={() => router.push(`/services/${item.id}` as any)} style={[styles.category, { backgroundColor: colors.surface, borderColor: colors.border, width: `${100 / cols - 2}%` }]}><View style={styles.imageFrame}><Image source={item.image} style={styles.categoryImage} contentFit="contain" /></View><Text style={[styles.cardTitle, { color: colors.textPrimary }]}>{localize(language, item.name)}</Text><View style={styles.count}><Text style={styles.countText}>{servicesCounts[item.id as keyof typeof servicesCounts]}</Text></View></Pressable>}
      ListFooterComponent={<View><Text style={[styles.sectionTitle, { color: colors.textPrimary, textAlign: isAr ? 'right' : 'left' }]}>{lb('Discover', 'À découvrir', 'اكتشف')}</Text><Pressable onPress={() => router.push(`/services/restaurant/${restaurant.id}` as any)} style={[styles.feature, isAr && styles.rtl, { backgroundColor: colors.surface }]}><Image source={restaurant.cover} style={styles.featureImage} contentFit="cover" /><View style={styles.featureInfo}><Text style={[styles.featureTitle, { color: colors.textPrimary, textAlign: isAr ? 'right' : 'left' }]}>{localize(language, restaurant.name)}</Text><Text style={[styles.quote, { color: colors.textSecondary, textAlign: isAr ? 'right' : 'left' }]}>{lb('Local flavors, delivered warm.', 'Saveurs locales, livrées chaudes.', 'نكهات محلية تصلك ساخنة.')}</Text><Rating rating={restaurant.rating} reviews={restaurant.reviews} color={colors.textSecondary} /><Text style={[styles.quote, { color: colors.textSecondary }]}>{restaurant.city}</Text></View></Pressable><Pressable onPress={() => router.push(`/services/book/${book.id}` as any)} style={[styles.feature, isAr && styles.rtl, { backgroundColor: colors.surface }]}><Image source={book.cover} style={styles.featureImage} contentFit="cover" /><View style={styles.featureInfo}><Text style={[styles.featureTitle, { color: colors.textPrimary, textAlign: isAr ? 'right' : 'left' }]}>{localize(language, book.title)}</Text><Text style={[styles.quote, { color: colors.textSecondary }]}>{book.author}</Text><Rating rating={book.rating} reviews={book.reviews} color={colors.textSecondary} /><Text style={styles.price}>{money(book.price)}</Text></View></Pressable></View>}
    /></KeyboardAvoidingView>
  </SafeAreaView>;
}
const styles = StyleSheet.create({ safe:{flex:1},header:{paddingHorizontal:scale(14),paddingBottom:scale(12)},headerTitle:{fontFamily:'Cairo-Bold',fontSize:scale(23),color:'#FFF',paddingVertical:scale(8)},search:{height:scale(48),borderRadius:scale(24),backgroundColor:'#FFF',flexDirection:'row',alignItems:'center',paddingHorizontal:scale(15),gap:8},rtl:{flexDirection:'row-reverse'},input:{flex:1,fontFamily:'Cairo-Regular',fontSize:scale(14),color:'#111827'},gridRow:{justifyContent:'space-between',gap:scale(12)},category:{borderRadius:scale(16),borderWidth:1,padding:scale(9),alignItems:'center',marginBottom:scale(12),minHeight:scale(190)},imageFrame:{height:scale(112),width:'100%',borderRadius:scale(12),backgroundColor:'#FFF',overflow:'hidden'},categoryImage:{width:'100%',height:'100%'},cardTitle:{fontFamily:'Cairo-SemiBold',fontSize:scale(13),textAlign:'center',marginTop:scale(7),minHeight:scale(38)},count:{backgroundColor:'#EEEAFE',paddingHorizontal:scale(12),paddingVertical:3,borderRadius:12},countText:{fontFamily:'Cairo-Bold',fontSize:scale(11),color:PURPLE},sectionTitle:{fontFamily:'Cairo-Bold',fontSize:scale(19),marginVertical:scale(12)},feature:{flexDirection:'row',borderRadius:scale(16),padding:scale(10),marginBottom:scale(12),gap:scale(12)},featureImage:{width:scale(106),height:scale(106),borderRadius:scale(12)},featureInfo:{flex:1,justifyContent:'center',gap:3},featureTitle:{fontFamily:'Cairo-Bold',fontSize:scale(14)},quote:{fontFamily:'Cairo-Regular',fontSize:scale(12)},price:{fontFamily:'Cairo-Bold',fontSize:scale(14),color:PURPLE} });
