import React, { useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { Image } from 'expo-image';
import { MaterialIcons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useApp } from '@/contexts/AppContext';
import { BOTTOM_NAV_CONTENT_GAP, scale } from '@/constants/responsive';
import { MEALS, RESTAURANTS, Meal } from '@/services/servicesHub';
import { localize, money, PURPLE, Rating, ServiceHeader } from '@/components/services/ServicePrimitives';

export default function RestaurantDetail(){const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const insets=useSafeAreaInsets();const {colors,language}=useApp();const isAr=language==='ar';const lb=(en:string,fr:string,ar:string)=>language==='fr'?fr:isAr?ar:en;const r=RESTAURANTS.find(x=>x.id===id);const [meal,setMeal]=useState<Meal|null>(null);const [extras,setExtras]=useState<string[]>([]);const [confirmed,setConfirmed]=useState(false);if(!r)return <SafeAreaView style={{flex:1,backgroundColor:colors.background}}><ServiceHeader title={lb('Restaurant not found','Restaurant introuvable','المطعم غير موجود')} isAr={isAr}/></SafeAreaView>;const meals=MEALS.filter(m=>m.restaurantId===r.id);const extrasTotal=meal?.extras.filter(x=>extras.includes(x.id)).reduce((n,x)=>n+x.price,0)||0;const subtotal=(meal?.price||0)+extrasTotal;const text={textAlign:(isAr?'right':'left') as 'right'|'left'};return <SafeAreaView edges={['top']} style={[s.safe,{backgroundColor:PURPLE}]}><ServiceHeader title={localize(language,r.name)} isAr={isAr}/><ScrollView style={{backgroundColor:colors.background}} contentContainerStyle={{paddingBottom:insets.bottom+scale(80)+BOTTOM_NAV_CONTENT_GAP}}><Image source={r.cover} style={s.cover}/><View style={[s.hero,{backgroundColor:colors.surface}]}><Image source={r.logo} style={s.logo}/><Pressable style={s.follow}><Text style={s.followText}>{lb('Follow','Suivre','متابعة')}</Text></Pressable><View style={[s.nameRow,isAr&&s.rtl]}><Text style={[s.title,{color:colors.textPrimary},text]}>{localize(language,r.name)}</Text>{r.verified&&<MaterialIcons name="verified" size={20} color="#2563EB"/>}</View><Rating rating={r.rating} reviews={r.reviews} color={colors.textSecondary}/><Text style={[s.meta,{color:colors.textSecondary},text]}>{r.city} · 🏍 {r.etaMin}–{r.etaMax} min · {money(r.deliveryFee)}</Text></View><Text style={[s.section,{color:colors.textPrimary},text]}>{lb('Menu','Menu','القائمة')}</Text>{meals.map(m=><View key={m.id} style={[s.meal,isAr&&s.rtl,{backgroundColor:colors.surface}]}><Image source={m.image} style={s.mealImage}/><View style={{flex:1,gap:4}}><Text style={[s.mealName,{color:colors.textPrimary},text]}>{localize(language,m.name)}</Text><Text style={s.price}>{money(m.price)}</Text><Text style={[s.badge,{color:m.available?'#166534':'#991B1B',backgroundColor:m.available?'#DCFCE7':'#FEE2E2'}]}>{m.available?lb('Available','Disponible','متاح'):lb('Unavailable','Indisponible','غير متاح')}</Text><Pressable disabled={!m.available} onPress={()=>{setMeal(m);setExtras([]);setConfirmed(false)}} style={[s.order,!m.available&&{opacity:.45}]}><Text style={s.orderText}>{lb('Order','Commander','اطلب')}</Text></Pressable></View></View>)}<Text style={[s.demo,{color:colors.textSecondary}]}>{lb('Demo data','Données de démonstration','بيانات تجريبية')}</Text></ScrollView>
<Modal visible={!!meal} transparent animationType="slide" onRequestClose={()=>setMeal(null)}><View style={s.overlay}><View style={[s.sheet,{backgroundColor:colors.surface,paddingBottom:insets.bottom+16}]}><View style={[s.sheetHead,isAr&&s.rtl]}><Text style={[s.section,{color:colors.textPrimary,margin:0}]}>{confirmed?lb('Order sent','Commande envoyée','تم إرسال الطلب'):lb('Order preview','Aperçu de la commande','معاينة الطلب')}</Text><Pressable onPress={()=>setMeal(null)} style={s.close}><MaterialIcons name="close" size={24} color={colors.textPrimary}/></Pressable></View>{confirmed?<Text style={[s.notice,{color:'#166534'}]}>{lb('The restaurant will confirm your order.','Le restaurant confirmera votre commande.','سيؤكد المطعم طلبك.')}</Text>:meal&&<><Text style={[s.mealName,{color:colors.textPrimary},text]}>{localize(language,meal.name)}</Text>{meal.extras.map(x=><Pressable key={x.id} onPress={()=>setExtras(v=>v.includes(x.id)?v.filter(i=>i!==x.id):[...v,x.id])} style={[s.extra,isAr&&s.rtl]}><MaterialIcons name={extras.includes(x.id)?'check-box':'check-box-outline-blank'} size={24} color={PURPLE}/><Text style={[s.meta,{color:colors.textPrimary,flex:1},text]}>{localize(language,x.name)}</Text><Text style={[s.meta,{color:colors.textPrimary}]}>{money(x.price)}</Text></Pressable>)}<View style={s.separator}/>{[[lb('Subtotal','Sous-total','المجموع الفرعي'),subtotal],[lb('Delivery fee','Frais de livraison','رسوم التوصيل'),r.deliveryFee],[lb('Total','Total','الإجمالي'),subtotal+r.deliveryFee]].map(([a,b])=><View key={String(a)} style={[s.total,isAr&&s.rtl]}><Text style={[s.meta,{color:colors.textPrimary}]}>{a}</Text><Text style={[s.mealName,{color:colors.textPrimary}]}>{money(Number(b))}</Text></View>)}<Pressable onPress={()=>setConfirmed(true)} style={s.confirm}><Text style={s.orderText}>{lb('Confirm order','Confirmer','تأكيد الطلب')}</Text></Pressable></>}</View></View></Modal></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1},rtl:{flexDirection:'row-reverse'},cover:{width:'100%',height:scale(205)},hero:{padding:16,paddingTop:38,marginBottom:8},logo:{position:'absolute',top:-34,left:16,width:68,height:68,borderRadius:34,borderWidth:3,borderColor:'#FFF'},follow:{position:'absolute',right:14,top:10,minHeight:48,paddingHorizontal:20,borderRadius:24,borderWidth:1,borderColor:PURPLE,justifyContent:'center'},followText:{fontFamily:'Cairo-Bold',fontSize:12,color:PURPLE},nameRow:{flexDirection:'row',gap:5,alignItems:'center'},title:{fontFamily:'Cairo-Bold',fontSize:20,flexShrink:1},meta:{fontFamily:'Cairo-Regular',fontSize:12},section:{fontFamily:'Cairo-Bold',fontSize:18,margin:14},meal:{marginHorizontal:14,marginBottom:12,borderRadius:16,padding:10,flexDirection:'row',gap:12},mealImage:{width:112,height:122,borderRadius:12},mealName:{fontFamily:'Cairo-Bold',fontSize:14},price:{fontFamily:'Cairo-Bold',fontSize:14,color:PURPLE},badge:{alignSelf:'flex-start',fontFamily:'Cairo-SemiBold',fontSize:10,paddingHorizontal:8,paddingVertical:3,borderRadius:9},order:{minHeight:48,borderRadius:12,backgroundColor:PURPLE,alignItems:'center',justifyContent:'center'},orderText:{fontFamily:'Cairo-Bold',fontSize:14,color:'#FFF'},demo:{fontFamily:'Cairo-Regular',fontSize:12,textAlign:'center',padding:20},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.55)',justifyContent:'flex-end'},sheet:{borderTopLeftRadius:24,borderTopRightRadius:24,padding:16},sheetHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},close:{width:48,height:48,alignItems:'center',justifyContent:'center'},extra:{minHeight:48,flexDirection:'row',alignItems:'center',gap:8},separator:{height:1,backgroundColor:'#E2E8F0',marginVertical:8},total:{flexDirection:'row',justifyContent:'space-between',paddingVertical:5},confirm:{minHeight:52,borderRadius:14,backgroundColor:PURPLE,alignItems:'center',justifyContent:'center',marginTop:12},notice:{fontFamily:'Cairo-SemiBold',fontSize:14,padding:18,textAlign:'center'}});
